name: deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a multi-line script
        run: |
          cd /home/zom/namsosadv
          git pull
          npm i
          sudo systemctl restart namsosadv